# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'

- script: ng lint
  displayName: 'Lint Validation'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
    publishLocation: 'filePath'
    targetPath: 'D:\a\r1\a\**\'

# Will need to run unit test using mocha and chai, azure agent can not open chrome. 
# - script: ng test
#   displayName: 'Unit Test'

# - script: ng e2e
#   displayName: 'End to End UI Test'
